### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by jalt007** [justintaddei/illusory#18] opened 2020-09-06 19:29 UTC
Great work on this! Was testing [the demo](https://justintaddei.github.io/illusory/) in Safari (both macOS & iOS) & the animations aren't working the same in Chrome...

![demo-animation-error](https://user-images.githubusercontent.com/70859946/92333658-393c7e00-f07f-11ea-8dce-e54d000d8829.gif)

No errors in the console so far.

Will dig around, but any idea what could be causing the issue?

**Comment by justintaddei** [comment] 2020-09-06 19:54
That's really strange. I know it was working prior to v2.0.0 and I could've sworn I tested it on iOS before the release.
Why is it always WebKit . . .

I've been able to replicate the issue on my iPhone but I don't own a Mac so debugging is a little tricky.

My first bet would be here: [src/deltaHandlers/transformHandler.ts](https://github.com/justintaddei/illusory/blob/master/src/deltaHandlers/transformHandler.ts) 

"Delta Handlers" take the computed styles from both elements and return a style that accounts for the delta between them (basically just a FLIP animation).

As of v2, the transform handler computes the transform matrix and combines the delta transform so that pre-existing transforms are accounted for.  I know that it's being computed because `#start` rotates back to `0deg`. But as to why `translate` it's being ignored I have no clue. 

Will you set a breakpoint inside the `transformHandler` function?
Found here: https://github.com/justintaddei/illusory/blob/703aca152e6cb5c64975aa69458cb1bc64f0c4f0/src/deltaHandlers/transformHandler.ts#L6

It expects two parameters, `delta` and `deltaStyle`.  
- `delta` is the difference between the elements (using `getBoundingClientRect`)
- `deltaStyle` is the computed `transform` style of the other element.

If those aren't the same as Chrome, it means the issue is with `window.getComputedStyle`. If they do match, however, the issue is likely with how Safari interprets transform matrixes.

**Comment by jalt007** [comment] 2020-09-06 21:00
Nice yeah it can be PITA especially without access to a mac, appreciate the explanation & pointers...

So far I've found `x` & `y` of the delta object are `NaN`. Bit slow with this so bare with, looking into why...

**Comment by jalt007** [comment] 2020-09-06 21:31
Yes seems the issue is with `getComputedStyle`, safari is returning an empty string for `transformOrigin` of `CSSStyleDeclaration`. Hmm...

**Comment by justintaddei** [comment] 2020-09-06 21:37
Okay, that actually makes a lot of sense. Just a second, I'm going to set up a Codesandbox.

**Comment by justintaddei** [comment] 2020-09-06 22:11
See if this fixes the issue: https://codesandbox.io/s/safari-ignores-translation-rz2d8 (click anywhere on the document to start the animation)

It turns out that transform-origin is actually the sort-hand for transform-origin-[x,y,z]. Who knew?
Anyway, browsers aren't required to report the computed style for short-hand properties (Chrome and Firefox do, but the Safari devs were lazy or something). I changed the source to get origin-x and origin-y instead.

Hope this works.

**Comment by jalt007** [comment] 2020-09-06 23:14
Interesting. The animation works in that codesandbox. But when making those changes in `getDelta` for the demo page on the example branch, the `transformOriginX` & `transformOriginY` return an empty string too (should have mentioned this before).

Can't immediately see what other values could be of use on that `CSSStyleDeclaration` object either...

**Comment by justintaddei** [comment] 2020-09-06 23:34
Wow..... okay, so the reason the Sandbox works is that I changed the parser to `return 0` if the origin string is falsely (i.e. it's not actually working).

It appears CSSStyleDeclaration only has `transformOrigin` and not the long-form properties (even though CSS does). So my original code is correct. I'll have to try and figure out why Safari doesn't report the origin.

**Comment by justintaddei** [comment] 2020-09-07 00:46
I think I got it!

The issue appears to be the in Safari, `window.getComputedStyle(...).cssText` doesn't include `transform-origin` even though `window.getComputedStyle(...).transformOrigin` exists.

The only change I made was to `src/utils/duplicateNode.ts`. I add the following below line 61:

```ts
target.style.transformOrigin = styles.transformOrigin;
```

Just manually setting the origin seemed to be enough. The problem appears to be fixed on my iPhone but I'll wait for you to confirm on your Mac before releasing a patch.

**Comment by jalt007** [comment] 2020-09-07 08:10
I can confirm that works. Nice one!! Cheers for your efforts.

**Comment by justintaddei** [comment] 2020-09-07 14:55
Thanks for your help debugging! It would've been a pain without a Mac.

I'm honestly surprised how easy of a fix it was. I just wish Safari would follow the spec for once 🙄

I'll incorporate the patch later today and close the issue after it's released

**Closed** 2020-09-08 07:22 UTC
Labels: bug

**Comment by justintaddei** [comment] 2020-09-08 07:35
The patch is live with the release of [v2.0.1](https://www.npmjs.com/package/illusory/v/2.0.1)

Thank you for contributing!
